### ISSUE TITLE
Flow-bin: Flow crashes when file is moved 

### ISSUE THREAD

**Issue by tbergq** [adeira/universe#104]
<img width="821" alt="Screenshot 2019-11-12 at 11 54 09" src="https://user-images.githubusercontent.com/7705041/68673282-a95b9f80-0553-11ea-8d8d-d87be6f0bf0e.png">

**Comment by tbergq** [comment]
Flow passed in the branch where this file was moved, but then it failed on CI on master.

**Comment by mrtnzlml** [comment]
Could you give me some steps to reproduce it locally, please? I know this is an issue but simply "moving a file" in a different branch doesn't do the trick. It's difficult to fix it without it.

**Comment by tbergq** [comment]
Well, you could try to go to one branch locally, move a file to a different folder. Commit, see that flow passes. Go back to master, merge your commit into master locally and run flow. Should fail

**Comment by mrtnzlml** [comment]
It doesn't do the trick for me. We need exact steps to reproduce it or at least to explain exactly why is it happening. I have some idea about it but I am not 100% sure yet.

**Comment by tbergq** [comment]
Ok, I don’t have any more exact steps at the moment. I will let you know if it happens again.

**Comment by mrtnzlml** [comment]
This issue is still there so I believe it will happen eventually. In such a case, please capture exactly what changed, how the files moved, how were the saved states cached and so on. As much information as possible.

**Comment by tbergq** [comment]
Will do

**Comment by aalises** [comment]
Hola! @mrtnzlml , this error also happened to me after renaming a file. I did not move it around any directory, just renaming.

The weird issue is that in the git diff log of the MR (in Gitlab), it does not show that the file was renamed but the old file is not there if I delete all local references of the branch and fetch it again.

**Comment by mrtnzlml** [comment]
Hi @aalises, are you able to provide exact steps to reproduce it locally?

**Comment by michalsanger** [comment]
We are not fixing this now, the workaround is to restart the cache.
