### ISSUE TITLE
eslint-runner: Show errors after warnings in our reporter

### ISSUE THREAD

**Issue by tbergq** [adeira/universe#1062]
It is not the best DX having to scroll through (possibly endless) warnings to find errors.

**Comment by mrtnzlml** [comment]
@tbergq Would it be possible to append a screenshot so we can imagine it? 📸

**Comment by tbergq** [comment]
> @tbergq Would it be possible to append a screenshot so we can imagine it? 📸

Screen capture maybe 🙈

**Comment by tbergq** [comment]
Screen capture shared on slack
