### ISSUE TITLE
New eslint rule `valid-test-folder`

### ISSUE THREAD

**Issue by tbergq** [adeira/universe#107]
I found a test in `__test__` which of course was never run and broken. 

We should probably also allow configuration of what is valid test folder name.

**Comment by mrtnzlml** [comment]
In this project? We use this simple scanner: https://github.com/adeira/universe/blob/master/src/monorepo-scanner/src/scans/TestsWithCorrectName.scan.js

It used to be more sophisticated (checking also the correct filename) but this is good enough as well.

**Comment by tbergq** [comment]
No, not in this project, elsewhere. I guess I can adopt the scanner into that project instead.

**Comment by mrtnzlml** [comment]
It could still be beneficial to have it as an Eslint plugin. Do you feel like doing it?

**Comment by tbergq** [comment]
I could try yes.
