### ISSUE TITLE
Improve intro page of docs

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#127]
This part of docs on intro page should be more welcoming:

<img width="774" alt="Screenshot 2019-11-17 01 08 40" src="https://user-images.githubusercontent.com/2174629/69000938-fb475100-08d6-11ea-9cd7-29aaff32a658.png">

**Comment by michalsanger** [comment]
@jaroslav-kubicek please specify how to make it more welcoming

**Comment by jaroslav-kubicek** [comment]
Here is proposal: https://github.com/adeira/universe/pull/503
