### ISSUE TITLE
Flow errors after upgrading @adeira/relay and @adeira/relay-runtime

### ISSUE THREAD

**Issue by jcolakk** [adeira/universe#1392]
Hi, after upgrading these two packages we get a handful of flow errors, 1049 to be precise. 
Some of the errors:

```
Cannot create `QueryRenderer` element because  `RequestIdentifier` [1] is incompatible with  string [2] in property `operation.fragment.owner.identifier` of the first argument of property `environment.__log`.Flow(incompatible-type)
RelayStoreTypes.js.flow(84, 16): [1] `RequestIdentifier`
RelayStoreTypes.js.flow(84, 16): [2] string
``` 
```
Cannot create `QueryRenderer` element because  `RelayObservable` [1] is incompatible with  `RelayObservable` [2] in property `source` of the first argument of property `environment.executeWithSource`.Flow(incompatible-type)
RelayStoreTypes.js.flow(635, 13): [1] `RelayObservable`
RelayStoreTypes.js.flow(635, 13): [2] `RelayObservable`
```

But it is only happening in test files, ie with mocked environment, so the problem could be in createMockEnvironment?

**Comment by tbergq** [comment]
Did you also update `relay-test-utils`?

**Comment by jcolakk** [comment]
Yes

**Comment by tbergq** [comment]
Can you check in `yarn.lock` that you don't have 2 versions installed, I get some similar errors if I downgrade `relay-test-utils`

**Comment by jcolakk** [comment]
only one version of relay-test-utils, but we do have multiple @adeira/relay and @adeira/relay-runtime versions and adding those to resolutions: 

```
"@adeira/relay-runtime": "0.18.0",
"@adeira/relay": "2.2.0"
```
makes it work 🤔

**Comment by tbergq** [comment]
I guess nitro still has dependencies of older versions of relay, I usually upgraded in nitro first, and then account next.

**Comment by tbergq** [comment]
So, I guess we can close this issue?

**Comment by jcolakk** [comment]
Yes, everything seems to work fine after adding them to resolutions, thanks 👍
