### ISSUE TITLE
Turn on "require-readonly-react-props"

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#140]
Let's fix todo and turn on https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-require-readonly-react-props

**Comment by mrtnzlml** [comment]
Did you read the reason why is it turned off? https://github.com/adeira/universe/blob/6ce48010de94ba83b07f9e938916146e94d5d8eb/src/eslint-config-adeira/ourRules.js#L270

See: https://github.com/gajus/eslint-plugin-flowtype/pull/400#issuecomment-492828739

**Comment by jaroslav-kubicek** [comment]
oh damn, ok
