### ISSUE TITLE
monorepo-run-tests not detecting file change in the root workspace

### ISSUE THREAD

**Issue by jcolakk** [adeira/universe#1433]
Hi, is there a way to set all tests to run when a file in root workspace changes. 

e.g when you change something in `setupTest.js` which is set in `jest.config.js`
Making a change in setupTest.js does not trigger all tests, which it should in my opinion. 
```
const commonProjectConfig = {
  globals: {
    __DEV__: true,
  },
  timers: "fake",
  setupFilesAfterEnv: [path.join(__dirname, "scripts", "setupTest.js")],
  transform: {
    "^.+\\.[jt]sx?$": "babel-jest",
  },
};
```

**Comment by michalsanger** [comment]
You can always call `yarn test-only --all` but I guess that’s not what you are looking for.

**Comment by tbergq** [comment]
> You can always call `yarn test-only --all` but I guess that’s not what you are looking for.

I guess you mean `yarn monorepo-run-tests --all`. 

This will definitely be a way to do it, though I guess it should be picked up and ran also on the CI. This is also how the eslint-runner works, some specific changes, like changes to `.eslintrc.js` or `package.json` triggers `lint --all`.

**Comment by jcolakk** [comment]
>You can always call yarn test-only --all but I guess that’s not what you are looking for.
True, but then we lose the ability to run tests for only changed files, which we want on the CI.

I even changed the `.jest.config.js`, but that also didnt trigger all tests 🤔

**Comment by tbergq** [comment]
Yes, so we should probably add similar logic like [this](https://github.com/adeira/universe/blob/master/src/eslint-runner/src/run.js#L54) to our tests runner, just check if the `.jest.config.js` file is changed.

@jcolakk Feel free to open a PR.

**Comment by mrtnzlml** [comment]
> just check if the .jest.config.js file is changed

@tbergq Just a note: it's not only about the config file but also about the file in `setupFilesAfterEnv` (and possibly other options) as this issue suggests.

**Comment by tbergq** [comment]
> > just check if the .jest.config.js file is changed
> 
> @tbergq Just a note: it's not only about the config file but also about the file in `setupFilesAfterEnv` (and possibly other options) as this issue suggests.

Yeah, that is true, it makes it a bit more complicated.

**Comment by tbergq** [comment]
@jcolakk it should be fixed now. Please let us know if it works for you. 

Also note [that you need to have setupFilesAfterEnv](https://github.com/adeira/universe/commit/adef538333367362e670f1df4a2bf8335a831b11#diff-73c6f57e8b897c9e01df967ee39f0d17a4bd3640694d471d987dab806ed94b95R206) in the root of your `.jest.config.js` export for this to be picked up. 

You might only have it under projects(if I remember correctly)
