### ISSUE TITLE
NPM publisher stopped working

### ISSUE THREAD

**Issue by mrtnzlml** [adeira/universe#1671]
Something changed and our NPM publisher stopped working, see: https://github.com/adeira/universe/actions?query=workflow%3A%22NPM+Publisher%22

Also, seems like `npm-registry-client` (which we use for the publishing) is not maintained anymore.

**Comment by michalsanger** [comment]
Do you have the NPM auth token? Can you run the linked PR to see if the NPM error provides some info?

**Comment by mrtnzlml** [comment]
> Do you have the NPM auth token? Can you run the linked PR to see if the NPM error provides some info?

I do not but I can generate a new personal one. Give me a sec, please.

**Comment by michalsanger** [comment]
Or we can merge the PR and see what will happen...

**Comment by mrtnzlml** [comment]
@michalsanger I tried and all got successfully published. 🙈 Let's merge it.

**Comment by mrtnzlml** [comment]
Reopening because it's still failing (unable to publish a new package):

<img width="752" alt="Screenshot 2021-02-01 at 07 38 53" src="https://user-images.githubusercontent.com/978368/106466416-948e6300-649b-11eb-8255-e8afef60f041.png">

**Comment by michalsanger** [comment]
So you want the workflow to fail but a failure of one package should not affect others?

**Comment by mrtnzlml** [comment]
@michalsanger That would be nice. I think more important is to know about the failure though and now it finishes "green" even though we are unable to publish the package.

**Comment by michalsanger** [comment]
The only remaining problem is this:
`❌ Skipping @adeira/sx-design because of NPM error: 403 Forbidden`

Could it be something with the token we use? Change in permissions scope on NPM side?

**Comment by mrtnzlml** [comment]
@michalsanger NPM publisher uses `automation` token (https://docs.npmjs.com/creating-and-viewing-access-tokens) and it doesn't work even when I generated a new one for myself and tried it manually. I think something changed in the NPM response and we have to adjust the logic. I don't see any other explanation. 🤔

**Comment by michalsanger** [comment]
"Fortunately" it's happening only when you want to publish new package.
