### ISSUE TITLE
Babel has issues with huge file in SX Tailwind

### ISSUE THREAD

**Issue by michalsanger** [adeira/universe#1825]
There is a huge `__generated__/tailwindStyles.js` in `@adeira/sx-tailwind` Babel is having issues with:
https://vercel.com/adeira/universe-sx-tailwind-website/2TXUQQz3fLhWkyTYsPyGQALVZNWz

Maybe it's not needed anymore, at least that big. Currently it's only used for classname suggestion and for that case a smaller file could be used.

**Comment by mrtnzlml** [comment]
Alternatively, splitting it into multiple smaller files would probably also do the job.
