### ISSUE TITLE
adeira-flow-bin fails on the CI

### ISSUE THREAD

**Issue by jcolakk** [adeira/universe#1852]
When running `adeira-flow-bin` on the pipeline, it breaks with:
```
Lost connection to the flow server (3 retries remaining)
The flow server is not responding (3 retries remaining): -
Error: There is no Flow server running in '/builds/frontend/account'.
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

But when running on flow locally, it works just fine. 
It is happening after upgrading dependencies, I tried upgrading dependencies one by one, starting from the most obvious one `flow-bin` but it seems that they are not the culprit. 

Any ideas what might be wrong?

**Comment by michalsanger** [comment]
What version of node do you have locally and on CI?

**Comment by jcolakk** [comment]
Locally: v12.20.1
On the CI we are using `node:12` image

**Comment by michalsanger** [comment]
Could you try version 14 please?

**Comment by jcolakk** [comment]
Unfortunately, still doesnt work. I can't imagine that a package upgrade could cause this but here are some of the packages I'm trying to upgrade: 
```
@adeira/eslint-config `^5.0.0` -> `^5.1.0`
@babel/core `^7.12.16` -> `^7.12.17`
flow-bin `^0.144.0` -> `^0.145.0`
stylelint `^13.10.0` -> `^13.11.0`
@babel/runtime `^7.12.13` -> `^7.12.18`
cypress `^6.4.0` -> `^6.5.0`
@babel/cli `^7.12.16` -> ^7.12.17"
next `^10.0.6` -> `^10.0.7`
core-js `^3.8.3` -> `^3.9.0` 
...
```

**Comment by jcolakk** [comment]
When updating flow-bin standalone, it passes. But when upgrading `@babel/cli to 7.13.0, @babel/core to 7.13.1, @babel/runtime to 7.13.4, @babel/register to 7.13.0`, could it be that the babel is the culprit?

**Comment by michalsanger** [comment]
There was a release of new minor version of Babel packages today with following hotfixes after few hours, but not sure it's related to your issue. 

We stopped supporting Node v12, that's why I suggested to use v14 on your CI. Other packages are also dropping v12, for example `is-ci` which is used in `@adeira/flow-bin`.

**Comment by jcolakk** [comment]
I tried upgrading to the newest babel versions, but still the same issue. 
>We stopped supporting Node v12, that's why I suggested to use v14 on your CI. Other packages are also dropping v12, for example is-ci which is used in @adeira/flow-bin.
Yeah I know, we're planning on migrating to Node v14 as well. But thanks anyway 🙂  

Just wish `flow` would have a more descriptive message than `There is no Flow server running`...

**Comment by michalsanger** [comment]
@jcolakk did you solve this somehow?

**Comment by tbergq** [comment]
I am just relaying info from a private chat here, but the issue seems to have solved itself. 

Possibly related to clearing out cache, as was the problem in #104

**Comment by mrtnzlml** [comment]
I created a PR to release the latest version we are using in Universe (mostly deps upgrades): https://github.com/adeira/universe/pull/1880

It will probably not do much though because this issue doesn't seem to be on our side.
