### ISSUE TITLE
@adeira/relay: fetch-schema script should support .babelrc

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#189]
When running adeira-fetch-schema on repository with `.babelrc` only, it fails to find babel config: 

```
adeira-fetch-schema --resource=https://graphql.kiwi.com
/Users/jaroslavkubicek/projects/nitrolib/node_modules/@babel/core/lib/config/partial.js:50
        throw Object.assign(new Error(`Babel was run with rootMode:"upward" but a root could not ` + `be found when searching upward from "${rootDir}"`), {
        ^

Error: Babel was run with rootMode:"upward" but a root could not be found when searching upward from "/Users/jaroslavkubicek/projects/nitrolib"
```

**Comment by mrtnzlml** [comment]
You should upgrade to Babel 7 properly by using project-wide configuration `babel.config.js`, see: https://babeljs.io/docs/en/config-files#project-wide-configuration

I encountered this issue as well on one project and I am not sure we should modify it in this package (it's simple, we'd have to use root mode `upward-optional`). It seems like a problem of the project where people ignore the new configuration system for Babel 7.

**Comment by jaroslav-kubicek** [comment]
of course 🙂  possible solution can be also upgrading error message explaining this :)

**Comment by mrtnzlml** [comment]
Sure, feel free to send a PR to Babel since this is nothing Universe specific. :)

**Comment by jaroslav-kubicek** [comment]
Closed via https://github.com/babel/babel/pull/10778

**Comment by mrtnzlml** [comment]
Very nice! 👍

**Comment by mrtnzlml** [comment]
This will also be allowed from our side: https://github.com/adeira/universe/pull/203 (if it goes through the review)

It's because the code which is enforcing the "upward" mode is necessary only for Universe development and should not affect our NPM users. So I changed my mind and now I think this issue is very valid.

Thank you for your contribution into Babel itself though - that's really great no matter this change! :)

**Comment by mrtnzlml** [comment]
Side note: I believe it's still valid to use project-wide config for Babel 7+ projects... :)
