### ISSUE TITLE
monorepo-npm-publisher: support custom babel.config.js

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#196]
I would like to use `@adeira/monorepo-npm-publisher` on different project, but it needs to be transpiled with additional babel plugins

Proposed solution:
- publisher will try to find `babel.config.js`
- if found, it will automatically add `'@adeira/babel-preset-adeira` if it's not present in presets
- if config already contains `'@adeira/babel-preset-adeira` preset, it will be replaced as follow to enable multiple targets: 
```
[
          '@adeira/babel-preset-adeira',
          {
            target,
          },
 ],
```

**Comment by mrtnzlml** [comment]
There is a TODO in the NPM publisher to always use Babel config of the package which is being published. That should do the job, right?

**Comment by jaroslav-kubicek** [comment]
yes, that's pretty much the goal - to fix this todo, except it should always use `@adeira/babel-preset-adeira` imho. otherwise builds with different targets wouldn't make sense.

The goal is to really reuse it on different project where I need to add additional project-specific babel plugins

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek Why it should always use this preset? I think we should follow the same behavior Babel behaves inside Universe which is essentially `upward-optional` root mode + `babelrcRoots`. 🤔 The default preset can be completely different in different projects.

**Comment by jaroslav-kubicek** [comment]
the nice thing about this tool is the ability to ship `.flow`, `.mjs` and `.js` files easily. I will look into it in more depth how to keep this advantage while having custom config

**Comment by mrtnzlml** [comment]
Check for example monorepo builder project - it does something similar (the builder already takes relevant Babel configs into account). My idea was to replicate this behavior even inside the NPM publisher. It should be quite straightforward and simple to change.

The envisioned result is that you can use NPM publisher anywhere while achieving exactly the behavior you want - to use the correct configs as you'd expect it.

**Comment by jaroslav-kubicek** [comment]
Ok, so how exactly would you implement that @mrtnzlml ?

I would 

1. resolve user's babel configs: https://babeljs.io/docs/en/next/babel-core.html#advanced-apis
1. make sure that `@adeira/babel-preset-adeira` is set as it's right now
1. passed this upgraded config to `transformFileSync`

**Comment by mrtnzlml** [comment]
Look at how `monorepo-builder` does it. You don't have to resolve the Babel config manually at all - Babel knows what configs to use so you should just configure it. Don't even set `@adeira/babel-preset-adeira` - that's irrelevant (you can see that `monorepo-builder` is not doing anything like this and it builds the projects correctly).

**Comment by mrtnzlml** [comment]
I see what was the issue you were trying to explain me here: how to transpile the code with targets `js`, `js-esm` and `flow`. I didn't get it from the comments. 🙈
