### ISSUE TITLE
Flow errors when using useRefetchableFragment

### ISSUE THREAD

**Issue by jcolakk** [adeira/universe#1975]
Hi 👋 when using `useRefetchableFragment`. I get this flow error:
![image](https://user-images.githubusercontent.com/42477419/110927786-5c91ff80-8326-11eb-9f65-fcd6a1f556fb.png)

Adding `require('./InboxTabsRefetchQuery.graphql.js').default` or impoting it with import syntax(`import InboxTabsRefetchQuery from './InboxTabsRefetchQuery.graphql.js'`) solves it but its autogenerated. I guess this isnt issue with @adeira per se, just wondering how to solve this. Any ideas?

**Comment by mrtnzlml** [comment]
Hi and thanks for the report! Happy to see you are pushing Relay Hooks! 🙂

I just wanted to acknowledge it and will check it today. We should be able to fix it on our side actually but I will check if it should be reported to the upstream as well or not.

**Comment by mrtnzlml** [comment]
OK, so, issue reported to the upstream (https://github.com/facebook/relay/issues/3404) and fixed it in `@adeira/relay` beforehand (https://github.com/adeira/universe/pull/1976). Please, have a look.
