### ISSUE TITLE
Relay compiler throwing an error after upgarding to @adeira/relay v3.2.0

### ISSUE THREAD

**Issue by jcolakk** [adeira/universe#2036]
Hi, after upgrading `@adeira/relay` to v3.2.0 I get this error: 

![image](https://user-images.githubusercontent.com/42477419/111968231-3a079f80-8af9-11eb-8511-38cc4be76782.png)

Any idea what might be the cause, I don't see anything changed regarding the compiler in the latest release notes 🤔

**Comment by jcolakk** [comment]
ah, I actually see this:

> relax signature verification when using adeira-relay-compiler - it no longer requires the signature but still verifies it if it exists

But from the actual commit changes, it shouldn't really cause this 🤔

**Comment by mrtnzlml** [comment]
Hi, I went through all the changes in `@adeira/relay` and I am having a hard time figuring out what would be causing such an issue. Most of the changes are to clean up things and not changing the behavior very much. 🤔 

Are you sure this package is the culprit? If so, could you please share with us some more debug information? Things like `relay.config.js`, actually installed Relay versions, paths to the GraphQL schema, any client GraphQL schemas, and so on. It's a bit challenging to help from the information in this report.

**Comment by jcolakk** [comment]
Hi, sorry for not providing more info. 

**relay.config.js**

```
// @flow

const customSchema = process.argv.find((i) => i.startsWith('--schema'));

const schema = customSchema === undefined ? './schema.graphql' : customSchema.split('=')[1];

module.exports = {
  // Configuration options accepted by the `relay-compiler` command-line tool and `babel-plugin-relay`.
  src: './src',
  schema,
  exclude: [
    '**/node_modules/**',
    '**/__mocks__/**',
    '**/__generated__/**',
    '**/backend/**',
    '**/__flowtests__/**',
    '**/AccountEnvironment.js',
    '**/cypress/**',
    '**/.next/**',
  ],
};
```

**relay-runtime versions** 
we have `relay-runtime` in resolutions set to `11.0.0` because some other dependencies had a lower version and causing mismatch with flow errors:
```
relay-runtime@10.0.1, relay-runtime@10.1.3, relay-runtime@11.0.0, relay-runtime@^11.0.0, relay-runtime@~10.0.0:
  version "11.0.0"
  resolved "https://registry.yarnpkg.com/relay-runtime/-/relay-runtime-11.0.0.tgz#cb3244dc4e2919a51fdcbedddd5d13a20cf393e8"
  integrity sha512-7oeyW4hulyK3p4eB63Rsllo/es83xflCAt2HMWCpH2q0fi21iJBR02kK3wCPM/yFwi3i0K83W+UksLFQdE0CaQ==
  dependencies:
    "@babel/runtime" "^7.0.0"
    fbjs "^3.0.0"
```
**react-relay versions**: 
```
react-relay@^11.0.0:
  version "11.0.0"
  resolved "https://registry.yarnpkg.com/react-relay/-/react-relay-11.0.0.tgz#385b629198596a1d1e7879e9c3577cf9e6b6b697"
  integrity sha512-6ehR4ADbbJzA4slrEkL3iNBNIpICrBUBx3/kKZJN9JMfVKnXeOV52KmryIV1wj8yJU+wbkueu4h05fdQLTAIhw==
  dependencies:
    "@babel/runtime" "^7.0.0"
    fbjs "^3.0.0"
    nullthrows "^1.1.1"
    relay-runtime "11.0.0"

react-relay@~10.0.0:
  version "10.0.1"
  resolved "https://registry.yarnpkg.com/react-relay/-/react-relay-10.0.1.tgz#7b7bf7dd9752165ab99ae0302db4b3e56c143970"
  integrity sha512-zgafqWphSGFPSJ/h23zPpFGZ4tzKyj8eQPLTeZEwdbtmqAFsAIjPS0zSCo2DcsaeylEgSrQDShttpKYyEUtRAg==
  dependencies:
    "@babel/runtime" "^7.0.0"
    fbjs "^1.0.0"
    nullthrows "^1.1.1"
    relay-runtime "10.0.1"
```

**local schema** 
which extends 2 types, nothing special: 
```
extend type User {
  hasFutureTrips: Boolean
  hasPastTrips: Boolean
  linkingToken: String
}

extend type Booking {
  deeplink: String
  searchDeeplink: String
}
```

**Comment by mrtnzlml** [comment]
I am still unable to see what could cause such an issue. There are 2 things I'd do being in your chair:

1. Try to resolve the issues with multiple Relay versions (not only `relay-runtime` and `react-relay` but also `relay-compiler`, `relay-config` and others). I can imagine having multiple versions could cause issues.
2. try to run the raw relay compiler in your setup (something like `yarn relay-compiler`) to see where the issue comes from. It would be a good step forward to know whether `@adeira/relay` is even involved in this issue or not.

Let us know when you get some more info. We might have some new ideas based on the results.

**Comment by jcolakk** [comment]
Definitely agree with the first point, I'll try to sort it out. 👍 
As for the second, I tried with the `relay-compiler`and it passed with no problems

**Comment by mrtnzlml** [comment]
Hi, did you have any luck debugging what's going on? It's a bit tricky for us since we cannot reproduce this issue.

**Comment by jcolakk** [comment]
Hi, I managed to resolve these resolutions and I've got another error 😅  so I think the different versions may have been the problem. 🤔 
But basically, now I've got an error saying that I have a duplicate query definition, but that query only appears in a workspace that is excluded from the relay compiler, so I'm currently trying to figure that out

**Comment by mrtnzlml** [comment]
I'd really like to help and resolve this issue. But it's not very transparent. Would you have time to create a small reproducible demo? It will help us to see what's going on and it could help you understand the issue as well.

I am also happy to accept a PR with a fix if you know what and how.

**Comment by jcolakk** [comment]
Sure, I'll try to create a reproducible demo later. 

I fixed the original error by resolving the resolutions, so that is solved.

But basically what is happening now is that relay is ignoring the `exclude` property.

![image](https://user-images.githubusercontent.com/42477419/113727604-91ab2b00-96f5-11eb-9d40-09fa112f1210.png)

In our repo, we do have duplicate query definition, but that whole workspace is ignored by `**/backend/**`.

**Comment by jcolakk** [comment]
Okay, I solved the issue by renaming the queries which were problematic. But I would still like to find out why the `exclude` was not working, maybe I'm misunderstanding how `exclude` should work?

**Comment by jcolakk** [comment]
Well, the exclude is still not working as it should. But its a different issue, I'll look into it when I have time, so you can close this one. Thanks for the help! :)

**Comment by mrtnzlml** [comment]
Alright, BTW you can already start experimenting with next gen Relay Rust compiler via `adeira-relay-compiler-experimental`. 🤓
