### ISSUE TITLE
@adeira/relay: npm install chmod error

### ISSUE THREAD

**Issue by bycaldr** [adeira/universe#2328]
## npm install returns chmod error:
![image](https://user-images.githubusercontent.com/8123172/116887738-eb3a4300-ac2a-11eb-8969-5a0b50190486.png)

### Environment
- Node v14.16.1, Mac OSX

**Comment by mrtnzlml** [comment]
Hi @bycaldr! Thank you very much for the report. 👍 There is a PR pending to fix this issue: https://github.com/adeira/universe/pull/2329

A new version will be released shortly after the PR is approved and merged.

**Comment by mrtnzlml** [comment]
This should be fixed now. Yarn users were not affected. Please, let us know in case of any other issues. 😎

**Comment by bycaldr** [comment]
> This should be fixed now. Yarn users were not affected. Please, let us know in case of any other issues. sunglasses

Thank you very much @mrtnzlml :pray:
