### ISSUE TITLE
monorepo-npm-publisher: fails when trying to publish react-native project

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#240]
On react-native project (not related), monorepo-npm-publisher fails while trying to publish to npm and request fails:

```
/Users/jaroslavkubicek/projects/incubator/node_modules/npm-registry-client/lib/publish.js:124
      client.log.error('publish', 'Failed PUT ' + (res && res.statusCode))
                 ^

TypeError: client.log.error is not a function
```

- ~Is this caused by our way how we use this package? or bug in lib itself?~ seems like npm-registry-client bug, reported: https://github.com/npm/npm-registry-client/issues/179

**Comment by tbergq** [comment]
Can you create an issue with `npm-registry-client` to check?

**Comment by mrtnzlml** [comment]
Follow this issue here: https://github.com/npm/npm-registry-client/issues/179 (nothing to do in Universe)
