### ISSUE TITLE
Flow: enable 'unsafe-addition' lint

### ISSUE THREAD

**Issue by mrtnzlml** [adeira/universe#395]
It was skipped here: https://github.com/adeira/universe/pull/393/files

See: https://github.com/facebook/flow/releases/tag/v0.118.0

**Comment by mrtnzlml** [comment]
Or maybe it's enabled by default and we have `0` errors. In this case, we should just confirm it.

**Comment by tbergq** [comment]
don’t we have all=error in our lint config? So all new rules should be on by default

**Comment by mrtnzlml** [comment]
I am not 100% sure if that means all the lints are being enabled. There used to be some lints which were opt-in if I remember correctly. But dunno, maybe.
