### ISSUE TITLE
monorepo-utils: "getTouchedWorkspaces" fails when run without yarn

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#436]
Consider a script in file `example.js` with the following code:

```
const { getTouchedWorkspaces } = require('@adeira/monorepo-utils');

const touchedWorkspaces = getTouchedWorkspaces();
console.log(touchedWorkspaces);
```

Running such file directly via node, `node example.js`, fails on unexpected char when we are parsing stdout of executed shell command as JSON.

The problem is that execution of `new ShellCommand(null, 'yarn', 'workspaces', 'info', '--json')`  -> execution of yarn on "top level" outputs additional noise:

```
yarn workspaces v1.22.0
{}
✨  Done in 0.05s.
```

**Comment by mrtnzlml** [comment]
What kind of failure is it? I don't understand it from the description.

@tbergq Didn't you fix something related to this issue?

**Comment by tbergq** [comment]
Not quite sure I understand it either. 

You can see what I did in [this commit](https://github.com/adeira/universe/commit/181b6a47f00e72e2f366b1fbbc99189b593f81b9). Not sure it was related, but it was somehow necessary since the return of `yarn workspaces info --json` changed with yarn 1.22.0.

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek Are you using `yarn policies set-version` and enforcing the right Yarn version?

**Comment by tbergq** [comment]
Ok, I understand the issue. Given that you write code that doesn't need to be transpiled, 

```
// test.js
const { getTouchedWorkspaces } = require('@adeira/monorepo-utils');

const touchedWorkspaces = getTouchedWorkspaces();
console.log(touchedWorkspaces);
```
and you run it with node test.js it fails

**Comment by tbergq** [comment]
Then running it with `yarn monorepo-babel-node test.js` works.

**Comment by tbergq** [comment]
I think this is related to the transpiled version of  ShellCommand rather than `getTouchedWorkspaces`

**Comment by jaroslav-kubicek** [comment]
oh damn, I hope I'm at least by 1 % better dev than the writer 🤦‍♂
