### ISSUE TITLE
Release @adeira/relay 0.1.0

### ISSUE THREAD

**Issue by mrtnzlml** [adeira/universe#45]
This means to release even other related packages (0.1.0) such as:

- [x] @adeira/fetch
- [x] @adeira/js
- [x] @adeira/logger
- [x] @adeira/monorepo-utils
- [x] @adeira/signed-source

We should go through and fix all legacy things and old names, however, this version should be more or less the same as before (before we start doing other changes - because of backward compatibility).

**Comment by tbergq** [comment]
`Fetch` and `js` is already released

**Comment by mrtnzlml** [comment]
#63
