### ISSUE TITLE
Flow: enable `experimental.enforce_local_inference_annotations` option

### ISSUE THREAD

**Issue by mrtnzlml** [adeira/universe#5030]
The goal of this task is to enable the following config option in `.flowconfig`:

```diff
- experimental.enforce_local_inference_annotations=false
+ experimental.enforce_local_inference_annotations=true
```

This project currently has 10 errors after enabling this option that must be fixed.

See Flow 0.184.0 release notes: https://github.com/facebook/flow/releases/tag/v0.184.0

## Acceptance criteria

1. The Flow option `experimental.enforce_local_inference_annotations` is enabled.
1. The PR follows the project conventions.
1. All CI checks pass, and all code review comments are addressed.

## Hits for successful completion of this task

1. Enable `experimental.enforce_local_inference_annotations` in `.flowconfig`.
1. Run `./x flow` to see the new errors (should be ~10)
1. Start investigating and fixing the errors by adding correct Flow annotations.

## How to install and run this project

```bash
git clone --depth=100 git@github.com:adeira/universe.git
cd universe
corepack enable

chmod +x ./x
./x install
```

To run JavaScript tests:

```bash
./x tests
```

For more information, please visit `README.md` located at the root of this project. If you get lost, you can also start a [new discussion](https://github.com/adeira/universe/discussions). 😎

**Comment by manastelavane** [comment]
Hello, I would like to work on this task
