### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by Akshatjaiswal5** [adeira/universe#5234]
It is in the guidelines of hacktoberfest2022 to have this file explaining the rules of contribution.

**Comment by mrtnzlml** [comment]
Hi @Akshatjaiswal5! 👋

Is this somehow affecting your contributions to Hacktoberfest 2022? 🤔 

I am just wondering whether this is a blocker for you or just an improvement.

**Comment by mrtnzlml** [comment]
Hi @Akshatjaiswal5! 👋 

I've decided not to include this. I believe that the instructions in README are more than enough to be able to run the project, and after that, I am _very_ benevolent in how the contribution is made. No special steps are currently needed. Nothing specific is required.

I might change my mind when there is something more to say than just "open a PR however you want".

Thanks for your understanding.
