### ISSUE TITLE
@adeira/fetch doesn't work without @babel/runtime

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#526]
When installed in a project with minimal setup or in the node environment, importing/requiring `@adeira/fetch` fails with following error:

```
Thrown:
Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
```

**Comment by mrtnzlml** [comment]
Can you use `@adeira/babel-preset-adeira` which solves these issues? We do not distribute runtime in every FE package because it would unnecessarily increase the final bundle size. At least that was the initial idea.

**Comment by mrtnzlml** [comment]
Alternatively, I am seriously considering to stop using the runtime Babel transform since even co-authors are reporting it as a bug. 🙈
