### ISSUE TITLE
Release stable '@adeira/graphql-global-id' 1.0.0

### ISSUE THREAD

**Issue by mrtnzlml** [adeira/universe#558]
I think it's time. We could maybe check this before doing so: https://github.com/adeira/universe/blob/4e573868d532d56b237683ef42f0ab42345d95e9/src/graphql-global-id/src/GlobalID.js#L30-L31

**Comment by michalsanger** [comment]
Just `isTypeOf` would be nice

**Comment by mrtnzlml** [comment]
Yes, that was my idea as well. I wanted to do something better with it but seems like simple rename will be enough. :)

**Comment by tbergq** [comment]
closed with #575
