### ISSUE TITLE
Shipit: make it reusable (via NPM)

### ISSUE THREAD

**Issue by mrtnzlml** [adeira/universe#6096]
_See related discussion: https://github.com/adeira/universe/discussions/2214_

This has been requested a few times in recent years, and I've also wished to do this. This issue describes the steps necessary to make this happen (and their estimated complexity):

- [x] Publish the project to NPM (easy)
- [x] Allow configuring `config` files location from outside (normal)¹
- [x] Onboard the first project and make sure everything works correctly (?)
- [x] Improve README to include this use-case (easy)

These steps are required to get this issue resolved. Optionally, these steps might be a good idea doing:

- [x] Allow configuring accounts from outside (normal)²
- [ ] Allow configuring `adeira-source-id` handle (normal)

At the same time, our CI configuration needs to be updated so we can keep continuing using Shipit without interruptions; see: https://github.com/adeira/universe/blob/01bc08593713d3583aa0e2dde80af79f8c90258f/.github/workflows/shipit.yml#L37-L38

There might be some other steps necessary which I didn't realize while writing this issue. The code itself is used daily, it's relatively well-maintained and easy to understand (considering the complexity of the problem it's solving). I can explain everything needed. 😎

---

¹ Currently, both `shipit` and `importit` binaries use `iterateConfigs` function that hardcodes the location of the config files; see: https://github.com/adeira/universe/blob/01bc08593713d3583aa0e2dde80af79f8c90258f/src/monorepo-shipit/src/iterateConfigs.js#L70

This should be easy to change. We could introduce something like `--configDirectory=` option.

---

² There are some places that users might want to configure, such as this one: https://github.com/adeira/universe/blob/01bc08593713d3583aa0e2dde80af79f8c90258f/src/monorepo-shipit/src/accounts.js#L4

Again, the solution is very straightforward: we need not introduce something like `--account=` option.

**Comment by itsdouges** [comment]
Is the monorepo setup for publishing to npm, so it would just be a matter of removing private: true? Do you use changesets to cut releases?

**Comment by mrtnzlml** [comment]
@itsdouges I can take care of publishing it to NPM - I know exactly what needs to be done. Basically:

- private: true -> false in package.json
- modify version to 0.1.0 in package.json
- add the workspace explicitly to this list: https://github.com/adeira/universe/blob/a380dc08c0b3ab41a68ccbef0294ae3ba0ed5be5/scripts/publishedPackages.json
- run `./x scan` and fix if there are any issues

It should publish itself automatically after merging these changes to master.

**Comment by itsdouges** [comment]
Hey mate can you explain how importit works. Why does it need a PR number?

**Comment by itsdouges** [comment]
What does the workflow look like for importit? Run CI for every PR and then you never actually merge it on the destination? What could it look like if you did merge it to destination?

**Comment by mrtnzlml** [comment]
> What does the workflow look like for importit? Run CI for every PR and then you never actually merge it on the destination? What could it look like if you did merge it to destination?

@itsdouges Imagine you have a monorepo, and from there, you export three child repositories:

```mermaid
graph TD;
    A[Monorepo]-->R1[Repo 1];
    A[Monorepo]-->R2[Repo 2];
    A[Monorepo]-->R3[Repo 3];
```

Once you receive PR to one of these child repositories, you import it back to the monorepo via Importit, run all tests on it, and merge it into the monorepo (not the child repo directly!). This way, you make sure that the change can be integrated well with the rest of the ecosystem, and this change will eventually get exported via Shipit so that the child repos and monorepo are all in sync.

You could run tests in the child repos as a first check. But you should not merge it directly because that would create a conflict in the future when Shipit is trying to export the latest changes. Basically, having a child repo out of sync is no fun and requires manual intervention (imagine that you are trying to apply changes from one codebase into another one but the code there is different). This is how it works on all Facebook OSS repositories that use the original `facebook/fbshipit` implementation, and I also recommend it.

I guess technically, you could run Shipit in the other direction, but the same problem applies - the destination repo (in this case, part of the monorepo) has to be read-only; otherwise, it can get out of sync, and it's not possible to perform the export/import automatically.

Does that answer your question?

**Comment by itsdouges** [comment]
Thanks that makes sense. And then I suppose you'd pass on the committer to ensure they get a contribution counted.

Does React/Relay use ShipIt still? I noticed in React they do merge PRs 🤔.

For now I'm very happy to just get ShipIt functional but I do want to swing back soon and get importit working. Just need to get my head around how it would work as a workflow.

**Comment by mrtnzlml** [comment]
> Thanks that makes sense. And then I suppose you'd pass on the committer to ensure they get a contribution counted.

The committer should be preserved. At least that's how it works for Shipit.

> Does React/Relay use ShipIt still? I noticed in React they do merge PRs 🤔.

React doesn't use `facebook/fbshipit` as far as I know. You can recognize it by searching for `fbshipit-source-id` handle in the commit description ([example](https://github.com/facebook/flow/commit/8c036b6646dd303b54f247fa3e5db53f9310c13f)).

> For now I'm very happy to just get ShipIt functional but I do want to swing back soon and get importit working. Just need to get my head around how it would work as a workflow.

Do you want to see it in action? Open a simple PR in https://github.com/adeira/shipit (some whitespace change or whatever) and I will import it here so you can see it.

**Comment by itsdouges** [comment]
Ah I just checked out Relay and I can see it there https://github.com/facebook/relay/pull/4314

Makes sense. So all changes flow from source, pull requests are generally only imported when desired (manual step) and when merged internally and ShipIt syncs the repo the pull request is then closed. The icing on the cake would be some GitHub app to automate the messaging/closing of pull requests/setting tags.

**Comment by mrtnzlml** [comment]
> The icing on the cake would be some GitHub app to automate the messaging/closing of pull requests/setting tags.

Agree, that would be really nice. The closing can be done automatically when the exported commit message contains something like _"Closes: https://..."_ (URL of the original PR).

**Comment by itsdouges** [comment]
@mrtnzlml hey for the differences to fbshipit can you explain this?

> - we currently cannot do this in one commit:
> - changed Shipit config: https://github.com/facebook/fbshipit/commit/939949dc1369295c910772c6e8eccbbef2a2db7f
> - effect in Relay repo: https://github.com/facebook/relay/commit/13b6436e406398065507efb9df2eae61cdc14dd9

**Comment by itsdouges** [comment]
_Also_ is there like a health check or something to test if a repo has any merge commits? What happens if it source repo has them currently when running shipit?

**Comment by itsdouges** [comment]
And then what about failure cases. Let's say I did accidentally merged a rebased commit to the destination repo. How do I fix it?

**Comment by mrtnzlml** [comment]
> hey for the differences to fbshipit can you explain this? What is happening in the one commit, removing something from shipit? What's the limitation on our end?

I am not sure if I remember correctly, but I think we cannot remove the mapping of some subfolders AND the actual subfolders at the same time because Shipit would not know how is the deletion mapped in the exported repo. I have never tried it though so perhaps we should remove this note (unless it's tested and explained better).

> Also is src/monorepo-shipit/bin/create-patch.js used anywhere? It doesn't look like it and I'm tempted to delete it.

Please leave it there for now. It is handy for creating test fixtures when you want to capture some specific commit details for testing.

> Also is there like a health check or something to test if a repo has any merge commits? What happens if it source repo has them currently when running shipit?

There is no health check. I am open to a new PR if you know how to test for it. I never tested what happens actually since I never had this use-case.

> And then what about failure cases. Let's say I did accidentally merged a rebased commit to the destination repo. How do I fix it?

I've had some failures before. The biggest issue is when the destination repo is out of sync. Shipit then fails and prints the patch that could not be applied. In this case, you have to manually sync the destination repo, which is the case for `facebook/relay` as well, see: https://github.com/facebook/relay/pull/2774

I admit, the tooling around this could be much better. It's a rare case if you know what you are doing and you have the rules set well (like in this monorepo). But as always: I am very open to improving it or at least listening to how it should be done better/differently.

**Comment by itsdouges** [comment]
Getting this error when running:

```
Error: Unable to find root package.json file.
    at findRootPackageJsonPath (/home/runner/work/triplex-monorepo/triplex-monorepo/node_modules/@adeira/monorepo-utils/src/findRootPackageJson.js:31:11)
```

It assumes the root package json has a workspaces value https://github.com/adeira/universe/blob/54cf74d7407e8e19c52798d5afa538d97f59b138/src/monorepo-utils/src/findRootPackageJson.js#LL48C22-L48C32 but that isn't the case in a pnpm monorepo (instead it uses a pnpm-workspace.yaml).

As a work around I'll see if I can just define it and move on.

**Comment by itsdouges** [comment]
Getting this error:

```
 git@github.com:try-triplex/shipit_test.git Error
Error: Command failed with exit code 128: fatal: bad revision '92a643d20f6961ab21f462787536d3d59cb0dbb8..origin/master'
```

Fresh repository. Anything I need to do? I'm testing in a pull request.

**Comment by itsdouges** [comment]
Hmm it's a problem with the first commit of the repository 

<img width="1246" alt="image" src="https://github.com/adeira/universe/assets/6801309/da2f9815-3388-4fb8-8e7a-e331f811eee6">

**Comment by mrtnzlml** [comment]
> It assumes the root package json has a workspaces value https://github.com/adeira/universe/blob/54cf74d7407e8e19c52798d5afa538d97f59b138/src/monorepo-utils/src/findRootPackageJson.js#LL48C22-L48C32 but that isn't the case in a pnpm monorepo (instead it uses a pnpm-workspace.yaml).
>
> As a work around I'll see if I can just define it and move on.

Interesting. Definitely an area for improvement. I am for removing this magic altogether and replacing it with something else (maybe even manual config).

> Yes that works. However the branch doesn't exist on the remote yet (it's an empty repository). Do I need to create a branch first?

I don't think you need to. I think I've never created this manually. Shipit should create a new one based on your configuration: https://github.com/adeira/shipit/blob/9a08af1dd066069e2bdaae71fae51b28ceeec5f3/src/RepoGit.js#L89

What you need to do is to invite your bot account to the exported repository and give it write access.

> Hmm it's a problem with the first commit of the repository

You mean you created this commit manually there, and now it doesn't work? Is there any code already in the commit? 🤔 

You can re-connect it to Shipit by, for example, creating an empty commit with a description containing the `adeira-source-id` magic string. It should point to the commit in the original repo with the same content as this exported repo. In other words, this handle says: this commit was exported from `adeira-source-id` original monorepo commit, start there and export everything that is new.

**Comment by itsdouges** [comment]
> You mean you created this commit manually there, and now it doesn't work? Is there any code already in the commit? 🤔

No the commit is on source. There's no commits on the destination yet, I've invited the bot account there, added its SSH private key to secrets, and ensured it has write access. 

I just don't seem to be able to get it past the sync phase:

```
git@github.com:try-triplex/triplex.git Error
Error: Command failed with exit code 128: fatal: bad revision '92a643d20f6961ab21f462787536d3d59cb0dbb8..main'
```

Initially I thought it was a mapping problem (as I was just trying to copy "everything" over and then strip files). So I updated my config to this:

```
module.exports = {
  getStaticConfig() {
    return {
      repository: "git@github.com:try-triplex/triplex.git",
    };
  },
  getPathMappings() {
    return new Map([
      ["apps", "apps"],
      ["examples", "examples"],
      ["packages", "packages"],
      [".eslintrc.json", ".eslintrc.json"],
      [".gitignore", ".gitignore"],
      [".prettierrc", ".prettierrc"],
      ["LICENSE", "LICENSE"],
      ["package.json", "package.json"],
      ["pnpm-lock.yaml", "pnpm-lock.yaml"],
      ["pnpm-workspace.yaml", "pnpm-workspace.yaml"],
      ["README.md", "README.md"],
    ]);
  },
  getStrippedFiles() {
    return new Set([
      /^\.github\/workflows\/release-electron\.yml/,
      /^.shipit/,
      /^apps\/electron/,
      /^packages\/bridge/,
      /^packages\/client/,
      /^packages\/server/,
      /^packages\/ws-client/,
      /^scripts/,
    ]);
  },
  getBranchConfig() {
    return {
      source: "main",
      destination: "test",
    };
  },
};
```

But same problem. Hmm.

**Comment by itsdouges** [comment]
Assuming the git log error is because of:

> The error message "bad revision" indicates that the local repository in your build doesn't contain one of the commits you're referencing.

What would be the case for this? I'm using `fetch-depth: 0` in CI. 🤔

**Comment by itsdouges** [comment]
Okay well running it directly on main instead of in a pull request gets past that which is promising (albeit I'd love to be able to test in a pull request)... but I'm getting these errors now:

```
git@github.com:try-triplex/triplex.git Error
Error: Command failed with exit code 128: error: packages/editor/package.json: does not exist in index
error: packages/editor/tsconfig.json: does not exist in index
error: packages/rpc/package.json: does not exist in index
error: packages/rpc/tsconfig.json: does not exist in index
error: packages/run/package.json: does not exist in index
error: packages/run/src/backend-server.ts: does not exist in index
error: packages/run/tsconfig.json: does not exist in index
hint: Use 'git am --show-current-patch=diff' to see the failed patch

    at ShellCommand.runSynchronously (/home/runner/work/triplex-monorepo/triplex-monorepo/node_modules/@adeira/shell-command/src/ShellCommand.js:108:18)
    at RepoGit.commitPatch (/home/runner/work/triplex-monorepo/triplex-monorepo/node_modules/@adeira/monorepo-shipit/src/RepoGit.js:161:82)
    at /home/runner/work/triplex-monorepo/triplex-monorepo/node_modules/@adeira/monorepo-shipit/src/phases/createSyncPhase.js:51:25
    at Set.forEach (<anonymous>)
    at phase (/home/runner/work/triplex-monorepo/triplex-monorepo/node_modules/@adeira/monorepo-shipit/src/phases/createSyncPhase.js:48:16)
    at /home/runner/work/triplex-monorepo/triplex-monorepo/node_modules/@adeira/monorepo-shipit/bin/shipit.js:43:5
    at Set.forEach (<anonymous>)
    at /home/runner/work/triplex-monorepo/triplex-monorepo/node_modules/@adeira/monorepo-shipit/bin/shipit.js:41:341
    at /home/runner/work/triplex-monorepo/triplex-monorepo/node_modules/@adeira/monorepo-shipit/src/iterateConfigs.js:35:7
    at Array.forEach (<anonymous>)
Error: Process completed with exit code 1.
```

**Comment by itsdouges** [comment]
https://stackoverflow.com/questions/19115772/what-to-do-if-git-am-fails-with-does-not-exist-in-index

> The patch was not created against the correct source tree.

How could this be the case? If you have a chance would love any insight. This is my current config:

```
module.exports = {
  getStaticConfig() {
    return {
      repository: "git@github.com:try-triplex/triplex.git",
    };
  },
  getPathMappings() {
    return new Map([
      ["apps", "apps"],
      ["examples", "examples"],
      ["packages", "packages"],
    ]);
  },
  getBranchConfig() {
    return {
      source: "main",
      destination: "test",
    };
  },
};
```

**Comment by itsdouges** [comment]
The initial commit isn't being picked up by this command in `findDescendantsPath`.

```
git log --reverse --ancestry-path --no-merges --pretty=tformat:%H 92a643d20f6961ab21f462787536d3d59cb0dbb8..origin/main
```

**Comment by itsdouges** [comment]
OK I was able to push something:

<img width="650" alt="image" src="https://github.com/adeira/universe/assets/6801309/f7b39dd5-0642-4861-ba93-f6a2b6fc09d0">

Here are the current summarized issues I'm facing:

1. Initial commits that aren't empty are skipped by the `findDescendantsPath` git command. This is because `git log --ancestory-path A..B` doesn't include the "A" commit. [Code here](https://github.com/adeira/shipit/blob/master/src/RepoGit.js#L220-L223).
2. `createVerifyRepoPhase()` check is failing the git diff for `git --no-pager diff --stat HEAD shipit_destination/master`, changing it to `git --no-pager diff --stat HEAD -- shipit_destination/master` resolves it but is that safe? [Code here](https://github.com/adeira/shipit/blob/master/src/phases/createVerifyRepoPhase.js#L85-L99).

And then while these aren't blocking I think this needs attention:

1. In `createVerifyRepoPhase()` check the git command has a hardcoded `master` in there. I have a feeling that instead should be the destination branch, no? [Code here](https://github.com/adeira/shipit/blob/master/src/phases/createVerifyRepoPhase.js#L85-L99).

**Comment by itsdouges** [comment]
Is there much left for this issue now?

- first external project has onboarded https://github.com/try-triplex/triplex/
- readme has been updated

**Comment by mrtnzlml** [comment]
@itsdouges I believe the issues you had are mostly resolved, correct? (https://github.com/adeira/universe/pull/6138)

Addressing the remaining comments:

> Is there any ability to strip issue/pull request ids from commit messages? As they don't exist in the destination repo.

There is now: https://github.com/adeira/universe/pull/6171

> If I want to add paths later during the shipit lifecycle, for example removing a stripped file check, I get Error: ❌ Repository is out of SYNC! - what is the appropriate way to "add" files that were originally stripped in a previous sync? Vice versa what if I were to add new path mappings and then run sync again? Currently nothing happens. Ideally it would sync the folders that have now been added. Not supported?

At the moment, I do it manually. I am not sure how to achieve this automatically, but I am open to changing this (if we have some good plan on how to do it first).

> Is it possible to keep commit dates the same as author dates?

It's possible now: https://github.com/adeira/universe/pull/6138

> Is there much left for this issue now?

Not really; I am ready to close this issue. Hopefully, I didn't miss anything important.

Please open a new issue or discussion if there is something specific that needs to be addressed or improved.

**Comment by mrtnzlml** [comment]
@itsdouges Thank you very much for helping with this issue. Happy Shipping! 😎
