### ISSUE TITLE
Shipit: Introduce custom filters 

### ISSUE THREAD

**Issue by itsdouges** [adeira/universe#6166]
As per https://github.com/adeira/universe/pull/6161#issuecomment-1565547107

This would:

- introduce the `getCustomShipitFilter` config options
- default them to an identity function
- add its usage into `getDefaultShipitFilter`
- rename `getDefaultShipitFilter` to `getShipitFilter`

In a follow up pull request:

- let's also remove the commit message transform code.
- add a default filter for commit messages consumers can import as use out of the box.

The proposed configuration:

```js
type ChangesetFilter = (Changeset) => Changeset;

getCustomShipitFilter(): ChangesetFilter {
  return (changeset: Changeset): Changeset => {
    // do whatever you want here, return modified `Changeset`
  }
}
```

**Comment by itsdouges** [comment]
@mrtnzlml would importit also need custom filters?

**Comment by mrtnzlml** [comment]
> @mrtnzlml would importit also need custom filters? Probably?

@itsdouges I think it could also be handy, yes. However, it won't be a 1:1 reverse of `getCustomShipitFilter`. For example, once you remove the description or modify the commit message in a Shipit phase, then you cannot expect to revert it in the Importit phase.

**Comment by itsdouges** [comment]
That makes sense. Two APIs in config then?

- getCustomShipitFilter
- getCustomImportitFilter

Let me know your thoughts on names.

**Comment by mrtnzlml** [comment]
> That makes sense. Two APIs in config then?
> 
> * getCustomShipitFilter
> * getCustomImportitFilter
> 
> Let me know your thoughts on names.

Yes, this sounds good to me.

**Comment by mrtnzlml** [comment]
Done in: https://github.com/adeira/universe/pull/6171
