### ISSUE TITLE
Shipit: Unable to import it - identity error

### ISSUE THREAD

**Issue by itsdouges** [adeira/universe#6169]
Hey mate! Running importit I'm getting this error. Is there a step I've missed? I haven't debugged yet hoping you might know. If not sure I'll start debugging on my end.

```
➜  triplex-monorepo git:(main) npx monorepo-importit --committer-name triplex-bot --committer-email 124734075+triplex-bot@users.noreply.github.com --repo-url git@github.com:try-triplex/triplex.git --pull-request-id 1
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'douges@Michaels-Laptop.(none)')
git@github.com:try-triplex/triplex.git Error
Error: Command failed with exit code 128.
    at ShellCommand.runSynchronously (/Users/douges/projects/triplex-monorepo/node_modules/@adeira/shell-command/src/ShellCommand.js:108:18)
    at RepoGit.commitPatch (/Users/douges/projects/triplex-monorepo/node_modules/@adeira/monorepo-shipit/src/RepoGit.js:170:78)
    at /Users/douges/projects/triplex-monorepo/node_modules/@adeira/monorepo-shipit/src/phases/createImportSyncPhase.js:43:18
    at Set.forEach (<anonymous>)
    at /Users/douges/projects/triplex-monorepo/node_modules/@adeira/monorepo-shipit/src/phases/createImportSyncPhase.js:41:16
    at /Users/douges/projects/triplex-monorepo/node_modules/@adeira/monorepo-shipit/bin/importit.js:53:313
    at Set.forEach (<anonymous>)
    at /Users/douges/projects/triplex-monorepo/node_modules/@adeira/monorepo-shipit/bin/importit.js:53:296
    at /Users/douges/projects/triplex-monorepo/node_modules/@adeira/monorepo-shipit/src/iterateConfigs.js:35:7
    at Array.forEach (<anonymous>)
➜  triplex-monorepo git:(shipit-import-github-try-triplex/triplex-pr-1)
```

**Comment by itsdouges** [comment]
Okay so it's because I don't have my git user set globally (just locally) and it doesn't like it. Setting it resolves the problem. After setting it I was able to push up a PR and merge it. 😄

Public pull request: https://github.com/try-triplex/triplex/pull/1
Merged commit: https://github.com/try-triplex/triplex/commit/1924488fe06edd0d20d4ee7f79c3227bc85f0004

Happy days!

**Comment by itsdouges** [comment]
@mrtnzlml looking through the commit for importit - does it actually need the committer args? They didn't seem to have been used.

**Comment by mrtnzlml** [comment]
@itsdouges It is used in `createClonePhase` via `exportedRepo.configure()`.

We could introduce a config file where you could offload these args.

**Comment by mrtnzlml** [comment]
Or perhaps we could modify this Importit part? I agree that it should not be necessary to set it explicitly. 🤔

**Comment by itsdouges** [comment]
If it's just cloning I'd imagine it's not needed (because it uses your local creds first for permission, no?) - we could put in stub values at the worst case?

**Comment by mrtnzlml** [comment]
Yes, I think it's not needed. This is an oversight.
