### ISSUE TITLE
Add safe guard for using id(opaque:false) without an alias

### ISSUE THREAD

**Issue by tbergq** [adeira/universe#767]
See #766 for more info. 

We could do this by adding an eslint rule or extending the adeira relay compiler

**Comment by mrtnzlml** [comment]
@tbergq I changed the title because you probably wanted to write "without an alias"? :)

**Comment by tbergq** [comment]
> @tbergq I changed the title because you probably wanted to write "without an alias"? :)

Yes, thank you, that was of course what I meant 😊
