### ISSUE TITLE
Setup Shipit for adeira.dev

### ISSUE THREAD

**Issue by mrtnzlml** [adeira/universe#82]
This essentially means to move content from https://github.com/adeira/adeira.github.io _into_ Universe and connect Shipit. Let me know if you need some more help.

**Comment by jaroslav-kubicek** [comment]
IMHO we can close this as https://github.com/adeira/adeira.github.io will contain only built version of docs

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek Is this still true even after you said you want to go with Docusaurus and Now.sh? In this case, we can keep all the sources here and just simply export it there (+connect it to Now).

**Comment by jaroslav-kubicek** [comment]
yes, docs will remain here and https://github.com/adeira/adeira.github.io will be removed

**Comment by jaroslav-kubicek** [comment]
ok, it will work differently in the end - docs will be synced with adeira.dev repo via shipit and there it will run gh action automatically to deploy to now.sh

-> let's setup shipit

**Comment by mrtnzlml** [comment]
> and there it will run gh action automatically to deploy to now.sh

Actually, we just click in Now.sh to connect the repository and it will work automatically (no need for the manual GH Actions).
