### ISSUE TITLE
@adeira/eslint-plugin: Add rule to check valid Flow mode values

### ISSUE THREAD

**Issue by michalsanger** [adeira/universe#925]
Currently there is no typo check for the Flow flag. Only these values should be allowed:
- `@flow`
- `@flow strict`
- `@flow strict-local`

It would help in #922

**Comment by mrtnzlml** [comment]
NB: I think good place could be our Eslint rule [no-invalid-flow-annotations](https://github.com/adeira/universe/blob/master/src/eslint-plugin-adeira/src/rules/no-invalid-flow-annotations.js)
